const passport = require('passport');
module.exports = app => {
	app.get(
		'/auth/google',
		passport.authenticate('google', { scope: ['profile', 'email'] })
	);

	app.get('/auth/google/callback', passport.authenticate('google'));

	app.get('/api/logout', (req, res) => {
		req.logout(); // this logout func is generated by passport to kill the cookie session
		res.send(req.user); // the user also from our work with passport and cookie-session(but it will send nothing here because we killed the session)
	});

	app.get('/api/current_user', (req, res) => {
		res.send(req.user);
	});
};
